version = 1

[[annotations]]
path = ["supply-chain/*", ".gitignore", "Cargo.lock"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright © 2025 hashcatHitman"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
